In [14]:
import numpy as np
import torch

np.random.seed(0)

x = np.random.rand(6).reshape(2,3)

x_tensor = torch.tensor(x)
x_from_numpy = torch.from_numpy(x)
x_Tensor = torch.Tensor(x)
x_as_tensor = torch.as_tensor(x)
x_tensor_grad = torch.tensor(x, requires_grad=True)

x[0,0] = 100

print(x, x.dtype)

print(x_tensor, x_tensor.dtype, x_tensor.requires_grad)

print(x_from_numpy, x_from_numpy.dtype, x_from_numpy.requires_grad)

print(x_Tensor, x_Tensor.dtype, x_Tensor.requires_grad)

print(x_as_tensor, x_as_tensor.dtype, x_as_tensor.requires_grad)

print(x_tensor_grad, x_tensor_grad.dtype, x_tensor_grad.requires_grad)

[[100.           0.71518937   0.60276338]
 [  0.54488318   0.4236548    0.64589411]] float64
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]], dtype=torch.float64) torch.float64 False
tensor([[100.0000,   0.7152,   0.6028],
        [  0.5449,   0.4237,   0.6459]], dtype=torch.float64) torch.float64 False
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]]) torch.float32 False
tensor([[100.0000,   0.7152,   0.6028],
        [  0.5449,   0.4237,   0.6459]], dtype=torch.float64) torch.float64 False
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]], dtype=torch.float64, requires_grad=True) torch.float64 True
